version: "3.9"

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations users &&
             python manage.py makemigrations posts &&
            #  python manage.py makemigrations stories &&
            #  python manage.py makemigrations umessages &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8080"
    environment:
      - ./.env
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    expose:
      - 5432
    restart: always

volumes:
  db_data: null
